import AppKit
import Combine
import CoreGraphics
import Foundation

@MainActor
final class ClipboardManager: ObservableObject {
    let store: ClipboardStore

    let settings: AppSettings
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int

    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    init(settings: AppSettings, store: ClipboardStore? = nil, pasteboard: NSPasteboard = .general) {
        self.settings = settings
        self.store = store ?? ClipboardStore()
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = .scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !ClipboardCaptureGate.shared.isSuppressed else {
            FileLogger.shared.info(.clipboard, "capture_skipped internal_selection_copy=true")
            return
        }
        guard !settings.clipboardPaused, let capture = captureCurrentPasteboard() else { return }
        store.add(capture)
    }

    @discardableResult
    func paste(_ entry: ClipboardEntry, into targetApplication: NSRunningApplication?) -> Bool {
        ClipboardCaptureGate.shared.suppress(for: 1.5)
        pasteboard.clearContents()
        var wroteContent = false
        if let text = entry.text {
            wroteContent = pasteboard.setString(text, forType: .string) || wroteContent
        }
        if let rtf = store.rtfData(for: entry) {
            wroteContent = pasteboard.setData(rtf, forType: .rtf) || wroteContent
        }
        if let image = store.imageData(for: entry) {
            wroteContent = pasteboard.setData(image, forType: .png) || wroteContent
            if let nsImage = NSImage(data: image), let tiff = nsImage.tiffRepresentation {
                _ = pasteboard.setData(tiff, forType: .tiff)
            }
        }
        lastChangeCount = pasteboard.changeCount
        guard wroteContent else { return false }

        targetApplication?.activate()
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) {
            guard AXIsProcessTrusted() else { return }
            let source = CGEventSource(stateID: .hidSystemState)
            let down = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: true)
            let up = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: false)
            down?.flags = .maskCommand
            up?.flags = .maskCommand
            down?.post(tap: .cghidEventTap)
            up?.post(tap: .cghidEventTap)
        }
        FileLogger.shared.info(.clipboard, "entry_paste_requested kind=\(entry.kind.rawValue) target_present=\(targetApplication != nil)")
        return true
    }

    private func captureCurrentPasteboard() -> ClipboardCapture? {
        guard let item = pasteboard.pasteboardItems?.first else { return nil }
        let types = Set(item.types)
        guard !Self.transientTypes.contains(where: types.contains) else {
            FileLogger.shared.info(.clipboard, "capture_skipped sensitive_type=true")
            return nil
        }
        let source = NSWorkspace.shared.frontmostApplication?.localizedName ?? "未知应用"

        if let imageData = normalizedPNG(from: item), imageData.count <= AppConstants.maximumClipboardImageBytes {
            return ClipboardCapture(
                kind: .image,
                text: item.string(forType: .string),
                rtfData: nil,
                imagePNGData: imageData,
                sourceApplication: source,
                contentHash: ClipboardHash.sha256(imageData)
            )
        }
        guard let text = item.string(forType: .string), let textData = text.data(using: .utf8),
              textData.count <= AppConstants.maximumClipboardTextBytes else { return nil }
        let rtf = item.data(forType: .rtf)
        return ClipboardCapture(
            kind: .text,
            text: text,
            rtfData: rtf,
            imagePNGData: nil,
            sourceApplication: source,
            contentHash: ClipboardHash.sha256(textData)
        )
    }

    private func normalizedPNG(from item: NSPasteboardItem) -> Data? {
        if let png = item.data(forType: .png) { return png }
        guard let tiff = item.data(forType: .tiff), let image = NSImage(data: tiff),
              let representation = image.tiffRepresentation.flatMap(NSBitmapImageRep.init(data:)),
              let png = representation.representation(using: .png, properties: [:]) else { return nil }
        return png
    }
}
